apiVersion: apps/v1
kind: Deployment
metadata:
  name: flixconvert
  namespace: flixconvert
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flixconvert
  template:
    metadata:
      labels:
        app: flixconvert
    spec:
      containers:
        - name: web
          image: IMAGE_PLACEHOLDER
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SECRET_KEY
          readinessProbe:
            httpGet: { path: "/", port: 8080 }
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: "/", port: 8080 }
            initialDelaySeconds: 15
            periodSeconds: 20
