apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flixconvert
  namespace: flixconvert
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "500m"
spec:
  rules:
    - host: <YOUR_DOMAIN>
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flixconvert
                port:
                  number: 80
