apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flixconvert
resources:
  - namespace.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
